[package]
name = "bevy_serialization_assemble"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_serialization_core = {workspace = true}

bevy_ecs = {workspace = true}
bevy_render = {workspace = true}
bevy_reflect = {workspace = true}
bevy_color = {workspace = true}
bevy_utils = {workspace = true}
derive_more = {workspace = true}
glam = {workspace = true}
nalgebra = {workspace = true}
urdf-rs = {workspace = true}
bevy_math = {workspace = true}