[package]
name = "bevy_serialization_extras"
version = "0.6.0"
edition = "2021"
repository = "https://github.com/rydb/bevy_serialization_extras"
readme = "README.md"
license = "MIT"
description = "A crate for managing serialization with moonshine_save + wrappers."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/*"
]

[workspace.dependencies]
bevy-inspector-egui = "0.27.0"
# bevy_camera_extras = "0.14"
bevy_ui_extras = "0.15"
bevy_rapier3d = "0.27"
rapier3d = "0.21.0"
bevy = "0.14"
bevy_ecs = "0.14"
bevy_core = "0.14"
bevy_input = "0.14"
bevy_render = "0.14"
bevy_app = "0.14"
bevy_reflect = "0.14"
bevy_pbr = "0.14"
bevy_utils = "0.14"
bevy_math = "0.14"
bevy_log = "0.14"
bevy_mod_raycast = "0.18"
bevy_obj = "0.14"
bevy_core_pipeline = "0.14"
bevy_asset = "0.14"
bevy_transform = "0.14"
bevy_window = "0.14"
bevy_color = "0.14"
moonshine-save = "0.3.9"
glam = "0.28"
ron = "0.8"
bevy_egui = "0.30"
egui = "0.29"
egui_extras = "0.29"
urdf-rs = "0.8.0"
multimap = "0.10"
strum = "0.26"
thiserror = "1.0"
strum_macros = "0.26"
bitflags = "2.4.1"
nalgebra = "0.33"
#serde = "1.0.*"
yaserde = "0.10"
derive_more = "0.99"
bitvec = "1.0"
#bevy_obj = "0.13"
log = "0.4.2"
bevy_serialization_core = {path = "./crates/bevy_serialization_core", version = "0.4.0"}
bevy_serialization_physics = {path = "./crates/bevy_serialization_physics", version = "0.4.0"}


[dependencies]
bevy_serialization_core = {workspace = true}
bevy_serialization_physics = {workspace = true}