[package]
name = "bevy_serialization_extras"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/rydb/bevy_serialization_extras"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11"}
rand = "0.8.5"
bevy_mod_raycast = "0.13.1"
bevy-inspector-egui = "0.19.0"
rapier3d = "0.17.2"
bevy_rapier3d = "0.22.0"
bevy_obj = "0.11.0"
urdf-rs = "0.7.1"
bevy_flycam = { git = "https://github.com/sburris0/bevy_flycam.git", rev = "4ed8bcebac4210f30c7d757c3fd2fba7a1d275e2"  }
thiserror = "1.0.40"
glam = "0.24.0"
ron = "0.8.0"
bevy_egui = "0.21.0"
bevy_window = "0.11.0"
egui = "0.22.0"
moonshine-save = { git = "https://github.com/Zeenobit/moonshine_save", rev="0ad1b69f966c344159c38c1033d458bf01c3c219"}
bevy_component_extras = "0.1"

[dev-dependencies]
bevy = {version = "0.11", features = ["dynamic_linking"]}
bevy_ui_extras = "*"
bevy_editor_extras = "*"