[package]
name = "bevy_serialization_extras"
version = "0.4.2"
edition = "2021"
repository = "https://github.com/rydb/bevy_serialization_extras"
readme = "README.md"
license = "MIT"
description = "A crate for managing serialization with moonshine_save + wrappers."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/*"
]

[dependencies]
bevy_serialization_core = {path = "./crates/bevy_serialization_core", version = "0.2.1"}
bevy_serialization_physics = {path = "./crates/bevy_serialization_physics", version = "0.2.1"}