[package]
name = "bevy_serialization_extras"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/rydb/bevy_serialization_extras"
readme = "README.md"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11"}
bevy_rapier3d = "0.22.0"
#urdf-rs = "0.7.1"
glam = "0.24.0"
ron = "0.8.0"
moonshine-save = { git = "https://github.com/rydb/moonshine_save", rev="b6fb1b0b287c8ea0808a8f0db2d095446b086731"}

strum = "0.25"
strum_macros = "*"

[dev-dependencies]
bevy = {version = "0.11", features = ["dynamic_linking"]}
bevy_ui_extras = "0.2"
bevy_editor_extras = "*"
bevy_mod_raycast = "0.14"
bevy-inspector-egui = "0.20.0"
bevy_component_extras = "0.1"
bevy_egui = "0.22"
egui = "0.23"