[package]
name = "bevy_serialization_extras"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/rydb/bevy_serialization_extras"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "A crate for managing serialization with moonshine_save + wrappers."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_rapier3d = "0.22"
glam = "0.24"
ron = "0.8"
moonshine-save = "0.3.3"
bevy_egui = "0.22"
egui = "0.23"
egui_extras = "0.23"

strum = "0.25"
strum_macros = "0.25"

[dev-dependencies]
bevy = {version = "0.11", features = ["dynamic_linking"]}
bevy_ui_extras = "0.2"
#bevy_editor_extras = "0.1"
bevy_mod_raycast = "0.14"
bevy-inspector-egui = "0.20.0"
bevy_component_extras = "0.1"

#[features]
#ui-utils = ["dep:egui", "dep:egui_extras", "dep:bevy_egui"]
#physics = ["dep:bevy_rapier3d"]